source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# AWSのS3を使うために必要
gem 'aws-sdk-s3', '~> 1.130.0'

# AWSのDynamoDBを使うために必要
gem 'aws-sdk-dynamodb', '~> 1.92.0'

# .envを読み込むために必要
gem 'dotenv', '~> 2.7.6'
