version: "3.7"
services:
  scraper:
    build: .
    container_name: scraper
    platform: linux/x86_64
    tty: true
    volumes:
      - ./src:/root/src
    command: /bin/bash
  db:
    image: mysql:8.0-debian
    container_name: mysql
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
