version: "3.7"
services:
  scraper:
    build: ./scraper/
    container_name: scraper
    platform: linux/x86_64
    tty: true
    volumes:
      - ./scraper/src:/root/src
    command: /bin/bash
  db:
    image: mysql:8.0-debian
    container_name: mysql
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql:/var/lib/mysql
  backend:
    build: ./backend/
    container_name: backend
    platform: linux/x86_64
    tty: true
    volumes:
      - ./backend/src:/root/app
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
