version: "3.7"
services:
  url_scraper:
    build: ./url_scraper/
    container_name: url_scraper
    platform: linux/x86_64
    # tty: true
    # volumes:
    #   - ./url_scraper/src:/root/src
    environment:
      TZ: 'Asia/Tokyo'
  info_scraper:
    build: ./info_scraper/
    container_name: info_scraper
    platform: linux/x86_64
    # tty: true
    # volumes:
    #   - ./info_scraper/src:/root/src
    environment:
      TZ: 'Asia/Tokyo'
  dbmanager_scraper:
    build: ./dbmanager_scraper/
    container_name: dbmanager_scraper
    platform: linux/x86_64
    # tty: true
    # volumes:
    #   - ./dbmanager_scraper/src:/root/src
    environment:
      TZ: 'Asia/Tokyo'
  backend:
    build: ./backend/
    container_name: backend
    platform: linux/x86_64
    tty: true
    volumes:
      - ./backend/src:/root/app
    ports:
      - 3000:3000
    environment:
      TZ: 'Asia/Tokyo'
  # backend_amazonlinux2:
  #   build: ./backend_amazonlinux2/
  #   container_name: backend_amazonlinux2
  #   platform: linux/x86_64
  #   tty: true
  #   volumes:
  #     - ./backend_amazonlinux2/src:/root/app
  #   ports:
  #     - 3000:3000
  #   environment:
  #     TZ: 'Asia/Tokyo'
  frontend:
    build: ./frontend/
    container_name: frontend
    platform: linux/x86_64
    tty: true
    volumes:
      - ./frontend/:/app/
    ports:
      - 3001:3000
    depends_on:
      - backend
