service: backend

provider:
  name: aws
  runtime: ruby3.2
  stage: prod
  region: ap-northeast-1
  environment:
    RAILS_ENV: production
    MY_AWS_REGION: ${ssm:/backend/dev/aws_region}
    MY_AWS_ACCESS_KEY_ID: ${ssm:/backend/dev/aws_access_key_id}
    MY_AWS_SECRET_ACCESS_KEY: ${ssm:/backend/dev/aws_secret_access_key}
    BACKEND_AWS_S3_BUCKET: ${ssm:/backend/dev/aws_s3_bucket_name}
    RAILS_LOG_TO_STDOUT: true

package:
  include:
    - vendor/bundle/**

functions:
  app:
    handler: lambda_function.lambda_handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors:
            origin: 'https://tapfindcase.com'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
