service: backend

provider:
  name: aws
  runtime: ruby3.2
  stage: ${opt:stage, 'dev'} # 本番環境に切り替えること!(prodと入れること！)
  region: ap-northeast-1
  environment:
    MY_AWS_REGION: ${ssm:/backend/dev/aws_region}
    MY_AWS_ACCESS_KEY_ID: ${ssm:/backend/dev/aws_access_key_id}
    MY_AWS_SECRET_ACCESS_KEY: ${ssm:/backend/dev/aws_secret_access_key}
    AWS_S3_BUCKET_NAME: ${ssm:/backend/dev/aws_s3_bucket_name}
    RAILS_LOG_TO_STDOUT: true

package:
  include:
    - vendor/bundle/**
functions:
  app:
    handler: lambda_function.lambda_handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'
