name: Build and Deploy to Lambda and API Gateway

on:
  push:
    branches:
      - main
    paths:
      - "Docker/backend/src/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Serverless CLI
        run: npm install -g serverless

      - name: Install Dependencies
        working-directory: Docker/backend/src
        run: bundle install

      - name: Deploy to Lambda and API Gateway
        working-directory: Docker/backend/src
        run: serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          BACKEND_AWS_S3_BUCKET: ${{ secrets.BACKEND_AWS_S3_BUCKET }}
