name: Build and Deploy to Lambda and API Gateway

on:
  pull_request:
    branches:
      - main
    paths:
      - "Docker/backend/src/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Serverless CLI
        run: npm install -g serverless

      - name: Install Dependencies
        working-directory: Docker/backend/src
        run: bundle install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Deploy to Lambda and API Gateway
        working-directory: Docker/backend/src
        run: serverless deploy
