name: CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "Docker/backend/src/**"

jobs:
  build-and-test:
    name: CI
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install necessary libraries
        run: sudo apt-get install libssl1.1 libssl-dev

      - name: Install Dependencies
        working-directory: Docker/backend/src
        run: bundle install

      - name: Run Rubocop
        working-directory: Docker/backend/src
        run: bundle exec rubocop

      - name: Run RSpec
        working-directory: Docker/backend/src
        run: bundle exec rspec

  deploy:
    name: CD
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Bundle install
        run: |
          cd Docker/backend/src
          bundle config set path 'vendor/bundle'
          bundle install --jobs 4 --retry 3

      - name: Install Serverless CLI
        run: npm install -g serverless

      - name: Deploy to Lambda and API Gateway
        working-directory: Docker/backend/src
        run: serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.MY_AWS_REGION }}
          BACKEND_AWS_S3_BUCKET: ${{ secrets.MY_BACKEND_AWS_S3_BUCKET }}
