source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# seleniumで動的サイトのスクレイピングに使用
gem 'selenium-webdriver', '~> 4.10'

# seleniumでchromium browserを動かすために必要
gem 'webdrivers', '~> 5.2'
